apiVersion: v1
kind: Service
metadata:
  name: fleetman-service

spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80        # Service's port
      NodePort: 30080 # Container's port
  type: NodePort      # Other options: NodePort, LoadBalancer, ExternalName
